services:
  db:
    image: postgres:15-alpine
    container_name: variables_engine_db
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      POSTGRES_DB: ${POSTGRES_DB:-variables_engine}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - variables_engine_network

  app:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: variables-engine-app
    ports:
      - "5001:5001"
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db/variables_engine
      - FLASK_ENV=development
      - FLASK_DEBUG=1
    volumes:
      - ..:/app
    depends_on:
      - db
    networks:
      - variables_engine_network

  adminer:
    image: adminer:latest
    container_name: variables_engine_adminer
    ports:
      - "8080:8080"
    environment:
      ADMINER_DEFAULT_SERVER: db
      ADMINER_DESIGN: nette
    depends_on:
      - db
    networks:
      - variables_engine_network

networks:
  variables_engine_network:
    driver: bridge

volumes:
  postgres_data: