version: '3.8'

services:
  postgres:
    image: postgres:16
    container_name: variables-engine-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: variablesengine
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  app:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: variables-engine-app
    ports:
      - "5000:5000"
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@postgres/variablesengine
      - FLASK_ENV=development
      - FLASK_DEBUG=1
    volumes:
      - ..:/app
    depends_on:
      postgres:
        condition: service_healthy

volumes:
  postgres_data: